config/routes.rb
Rails.application.routes.draw do
  resources :notification_types

  resources :conditions

  resources :notifications

  resources :services

  devise_for :users

  root to: "home#index"

  get 'home/index'
end

app/models/condition.rb
class Condition < ActiveRecord::Base
  belongs_to :notification_type

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :service

end

app/models/notification_type.rb
class NotificationType < ActiveRecord::Base
  belongs_to :service
  has_many   :conditions
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :notification_types

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notifications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conditions_controller.rb
class ConditionsController < InheritedResources::Base

  def permitted_params
    params.permit!
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notification_types_controller.rb
class NotificationTypesController < InheritedResources::Base

  def permitted_params
    params.permit!
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < InheritedResources::Base

  def new
    @notification_type = NotificationType.find(params[:notification_type])
    @notification = Notification.new
  end

  def permitted_params
    params.permit!
  end
end

app/controllers/services_controller.rb
class ServicesController < InheritedResources::Base

  def permitted_params
    params.permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notification_types_helper.rb
module NotificationTypesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/conditions/_form.html.erb
<%= simple_form_for(@condition) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :notification_type %>
    <%= f.input :description %>
    <%= f.input :input_type %>
    <%= f.input :html_control %>
    <%= f.input :required %>
    <%= f.input :values %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/conditions/edit.html.erb
<h1>Editing condition</h1>

<%= render 'form' %>

<%= link_to 'Show', @condition %> |
<%= link_to 'Back', conditions_path %>

app/views/conditions/index.html.erb
<h1>Listing conditions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Type</th>
      <th>Html control</th>
      <th>Required</th>
      <th>Values</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conditions.each do |condition| %>
      <tr>
        <td><%= condition.name %></td>
        <td><%= condition.description %></td>
        <td><%= condition.input_type %></td>
        <td><%= condition.html_control %></td>
        <td><%= condition.required %></td>
        <td><%= condition.values %></td>
        <td><%= link_to 'Show', condition %></td>
        <td><%= link_to 'Edit', edit_condition_path(condition) %></td>
        <td><%= link_to 'Destroy', condition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Condition', new_condition_path %>

app/views/conditions/new.html.erb
<h1>New condition</h1>

<%= render 'form' %>

<%= link_to 'Back', conditions_path %>

app/views/conditions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @condition.name %>
</p>

<p>
  <strong>Service:</strong>
  <%= @condition.notification_type.service.name %>
</p>

<p>
  <strong>Notification type:</strong>
  <%= @condition.notification_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @condition.description %>
</p>

<p>
  <strong>Input Type:</strong>
  <%= @condition.input_type %>
</p>

<p>
  <strong>Html control:</strong>
  <%= @condition.html_control %>
</p>

<p>
  <strong>Required:</strong>
  <%= @condition.required %>
</p>

<p>
  <strong>Values:</strong>
  <%= @condition.values %>
</p>

<%= link_to 'Edit', edit_condition_path(@condition) %> |
<%= link_to 'Back', conditions_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  <title><%= content_for?(:title) ? yield(:title) : "Getnotified" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,600,800' rel='stylesheet' type='text/css'>

  <%= javascript_include_tag "application" %>
</head>
<body>
<!-- Navigation & Logo-->
<div class="mainmenu-wrapper">
  <div class="container">
    <div class="menuextras">
      <div class="extras">
        <ul>
          <li><a href="page-login.html">Login</a></li>
        </ul>
      </div>
    </div>
    <nav id="mainmenu" class="mainmenu">
      <ul>
        <li>
          <a href="index.html"><h3>Get Notified</h3></a></li>
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <%= link_to "Services", services_path %>
        </li>
        <li class="has-submenu active">
          <a href="#">Pages +</a>
          <div class="mainmenu-submenu">
            <div class="mainmenu-submenu-inner">
              <div>
                <h4>Homepage</h4>
                <ul>
                  <li><a href="index.html">Homepage (Sample 1)</a></li>
                  <li><a href="page-homepage-sample.html">Homepage (Sample 2)</a></li>
                </ul>
              </div>
            </div><!-- /mainmenu-submenu-inner -->
          </div><!-- /mainmenu-submenu -->
        </li>
        <li>
          <a href="credits.html">Credits</a>
        </li>
      </ul>
    </nav>
  </div>
</div>

<!-- Page Title -->
<div class="section section-breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1><%= content_for?(:title) ? yield(:title) : "Other" %></h1>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

<!-- Footer -->
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-footer col-md-3 col-xs-6">
        <h3>Navigate</h3>
        <ul class="no-list-style footer-navigate-section">
          <li><a href="page-blog-posts.html">Blog</a></li>
          <li><a href="page-portfolio-3-columns-2.html">Portfolio</a></li>
          <li><a href="page-products-3-columns.html">eShop</a></li>
          <li><a href="page-services-3-columns.html">Services</a></li>
          <li><a href="page-pricing.html">Pricing</a></li>
          <li><a href="page-faq.html">FAQ</a></li>
        </ul>
      </div>

      <div class="col-footer col-md-4 col-xs-6">
        <h3>Contacts</h3>
        <p class="contact-us-details">
          <b>Address:</b> 123 Fake Street, LN1 2ST, London, United Kingdom<br/>
          <b>Phone:</b> +44 123 654321<br/>
          <b>Fax:</b> +44 123 654321<br/>
          <b>Email:</b> <a href="mailto:getintoutch@yourcompanydomain.com">getintoutch@yourcompanydomain.com</a>
        </p>
      </div>
      <div class="col-footer col-md-2 col-xs-6">
        <h3>Stay Connected</h3>
        <ul class="footer-stay-connected no-list-style">
          <li><a href="#" class="facebook"></a></li>
          <li><a href="#" class="twitter"></a></li>
          <li><a href="#" class="googleplus"></a></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="footer-copyright">&copy; 2013 mPurpose. All rights reserved.</div>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/notification_types/_form.html.erb
<%= simple_form_for(@notification_type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.association :service %>
    <%= f.input :account_required %>
    <%= f.association :conditions %>
    <%= f.input :featured %>
    <%= f.input :public %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/notification_types/edit.html.erb
<h1>Editing notification_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification_type %> |
<%= link_to 'Back', notification_types_path %>

app/views/notification_types/index.html.erb
<h1>Listing notification_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Service</th>
      <th>Account required</th>
      <th>Condition</th>
      <th>Featured</th>
      <th>Public</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notification_types.each do |notification_type| %>
      <tr>
        <td><%= notification_type.name %></td>
        <td><%= notification_type.description %></td>
        <td><%= notification_type.service.name %></td>
        <td><%= notification_type.account_required %></td>
        <td><%= notification_type.featured %></td>
        <td><%= notification_type.public %></td>
        <td><%= link_to 'Show', notification_type %></td>
        <td><%= link_to 'Edit', edit_notification_type_path(notification_type) %></td>
        <td><%= link_to 'Destroy', notification_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification type', new_notification_type_path %>

app/views/notification_types/new.html.erb
<h1>New notification_type</h1>

<%= render 'form' %>

<%= link_to 'Back', notification_types_path %>

app/views/notification_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @notification_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @notification_type.description %>
</p>

<p>
  <strong>Service:</strong>
  <%= @notification_type.service.name %>
</p>

<p>
  <strong>Account required:</strong>
  <%= @notification_type.account_required %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @notification_type.condition %>
</p>

<p>
  <strong>Featured:</strong>
  <%= @notification_type.featured %>
</p>

<p>
  <strong>Public:</strong>
  <%= @notification_type.public %>
</p>

<%= link_to 'Edit', edit_notification_type_path(@notification_type) %> |
<%= link_to 'Back', notification_types_path %>

app/views/notifications/_form.html.erb
<%= simple_form_for(@notification) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <% @notification_type.conditions.each do |cond| %>
      <label for="test"><%= cond.name %></label>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<h1>Listing notifications</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Service</th>
      <th>Type</th>
      <th>Conditions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.user %></td>
        <td><%= notification.service %></td>
        <td><%= notification.notif_type %></td>
        <td><%= notification.conditions %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p>
  <strong>User:</strong>
  <%= @notification.user %>
</p>

<p>
  <strong>Service:</strong>
  <%= @notification.service %>
</p>

<p>
  <strong>Type:</strong>
  <%= @notification.notif_type %>
</p>

<p>
  <strong>Conditions:</strong>
  <%= @notification.conditions %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>

app/views/services/_form.html.erb
<%= simple_form_for @service, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :url %>
  <%= f.input :logo_url %>
  <%= f.input :featured %>
  <%= f.input :public %>
  <%= f.input :account_required, as: :radio_buttons,
              collection: ["Yes", "Optional", "No"] %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                services_path, :class => 'btn' %>
  </div>
<% end %>

app/views/services/edit.html.erb
<%- model_class = Service -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/services/index.html.erb
<%- model_class = Service -%>
<% content_for :title, model_class.model_name.human.pluralize.titleize %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= link_to service.id, service_path(service) %></td>
        <td><%= service.name %></td>
        <td><%= service.description %></td>
        <td><%= service.url %></td>
        <td><%=l service.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_service_path(service), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      service_path(service),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_service_path,
            :class => 'btn btn-primary' %>

app/views/services/new.html.erb
<%- model_class = Service -%>
<% content_for :title, model_class.model_name.human.pluralize.titleize %>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/services/show.html.erb
<%- model_class = Service -%>
<% content_for :title, model_class.model_name.human.pluralize.titleize %>

<div class="service-header">
  <%= image_tag @service.logo_url, class: "service-logo" if defined?(@service.logo_url) %>
  <h1><%= @service.name %></h1>
  <blockquote>
    <p><%= @service.description %></p>
  </blockquote>
  Website: <%= link_to @service.url, @service.url %>
</div>

<div id="service-notifications" class="service-notifications">
  <h3>Notification Types</h3>
  <div class="container">
    <div class="row">
        <% @service.notification_types.each do |notif| %>
          <div class="col-md-4 col-sm-6">
            <div class="service-wrapper">
              <span class="mega-octicon octicon-star"></span>
              <h3><%= notif.name %></h3>
              <p><%= notif.description %>m</p>
              <%= link_to "Get Notified", new_notification_path(notification_type: notif.id), class: "btn" %>
            </div>
          </div>
        <% end %>
    </div>
  </div>

</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              services_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_service_path(@service), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              service_path(@service),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>